#!/bin/bash
#-------------------------------------------------------------------------------
#
# setup_root_env [ $DIRECTORY ]
#
#-------------------------------------------------------------------------------
# Properties

INIT_DIR=$1

if [ ! "$INIT_DIR" ]
then
  # Get the directory of this command.
  CMD_NAME=`basename $0`
  INIT_DIR=`which $CMD_NAME`
  
  if [ ! "$INIT_DIR" ]
  then
    cd `dirname $0`
    INIT_DIR=`pwd`
  
  else
    INIT_DIR=`dirname $INIT_DIR`  
  fi  
fi

#-------------------------------------------------------------------------------
# Start

echo "Copying default root shell environment."

cp -f "$INIT_DIR/overrides/root.profile" /root/.profile || exit 1
cp -f "$INIT_DIR/overrides/root.bashrc" /root/.bashrc || exit 2

echo "Including $INIT_DIR in root PATH variable."
echo -e "\nexport PATH=\$PATH:$INIT_DIR" >> /root/.bashrc || exit 3

cp -f "$INIT_DIR/overrides/user.bash_aliases" /root/.bash_aliases || exit 4