#!/bin/bash
#-------------------------------------------------------------------------------
#
# set_root_env
#
#-------------------------------------------------------------------------------
# Properties

HELP="
The set_root_env command initializes the root shell environment. 
WARNING: This script has only been tested with 8.04 LTS.

--------------------------------------------------------------------------------

 Developed by Adrian Webb of http://collectivecolors.com
 Licensed under GPL v2

 See the project page at:  http://github.com/collectivecolors/server-admin
 Report issues here:       http://github.com/collectivecolors/server-admin/issues
 
--------------------------------------------------------------------------------
"

USAGE="
usage: set_root_env [ -h | --help ]                # Show usage information
                    -------------------------------------------------------------
                    [ -o | --override-dir <dir> ]  # Directory that contains server overrides
                                                   # Defaults to <cmd-dir>/overrides
"


# Get the directory of this command.

CMD_NAME=`basename $0`
INIT_DIR=`which $CMD_NAME`

if [ ! "$INIT_DIR" ]
then
  CMD_NAME=`readlink -f $0`

  cd `dirname $CMD_NAME`
  INIT_DIR=`pwd`

else
  INIT_DIR=`readlink -f $INIT_DIR`
  INIT_DIR=`dirname $INIT_DIR`
fi

OVERRIDE_DIR="$INIT_DIR/overrides"  


# Parse parameters

while test $# -ne 0
do
	case "$1" in
	  
  -h|--help)
    echo "$HELP"
    echo "$USAGE"
    exit 0;;
  
	-o|--override-dir)
    if [ ! "$2" ] || [ ! -d "$2" ]
    then
      echo "Override directory option requires an existing directory name."
      echo "$USAGE"
      exit 1
    fi
    
		OVERRIDE_DIR="$2"
    shift;;
	  
	*) break;;
	esac
	shift
done


#-------------------------------------------------------------------------------
# Start

echo "Copying default root shell environment."

cp -f "$OVERRIDE_DIR/root.profile" /root/.profile || exit 2
cp -f "$OVERRIDE_DIR/root.bashrc" /root/.bashrc || exit 3
cp -f "$OVERRIDE_DIR/user.bash_aliases" /root/.bash_aliases || exit 4

echo "Successfully set root shell environment."