#!/bin/bash
#-------------------------------------------------------------------------------
#
# setup_default_user_env [ $DIRECTORY ]
#
#-------------------------------------------------------------------------------
# Properties

INIT_DIR=$1

if [ ! "$INIT_DIR" ]
then
  # Get the directory of this command.
  CMD_NAME=`basename $0`
  INIT_DIR=`which $CMD_NAME`
  
  if [ ! "$INIT_DIR" ]
  then
    cd `dirname $0`
    INIT_DIR=`pwd`
  
  else
    INIT_DIR=`dirname $INIT_DIR`  
  fi  
fi

#-------------------------------------------------------------------------------
# Start

echo "Copying default user shell environment."

cp -f "$INIT_DIR/overrides/user.profile" /etc/skel/.profile || exit 1
cp -f "$INIT_DIR/overrides/user.bashrc" /etc/skel/.bashrc || exit 2
cp -f "$INIT_DIR/overrides/user.bash_aliases" /etc/skel/.bash_aliases || exit 3