#!/bin/bash
#-------------------------------------------------------------------------------
# This script MUST be run by root on a freshly installed server.


#-------------------------------------------------------------------------------
# Change root password

echo "Resetting root password"
passwd || exit 1  # (repeat safe)


#-------------------------------------------------------------------------------
# Change main server settings

# Directory that contains all of the files for server initialization.
INIT_DIR=`pwd`
echo "$0"
echo `dirname "$0"`


# Set hostname. (repeat safe)
MY_HOSTNAME=''

echo -n "Enter hostname for this server: "
read MY_HOSTNAME
echo ''

if [ ! $MY_HOSTNAME ]
then
  echo "You must specify a hostname for this server."
  exit 2
fi

echo "Setting hostname to $MY_HOSTNAME"
echo -n $MY_HOSTNAME > /etc/hostname || exit 3

# Set locale. (repeat safe)
# TODO: Make this configurable
echo "Setting locale information."
locale-gen en_US.UTF-8 || exit 4
/usr/sbin/update-locale LANG=en_US.UTF-8 || exit 5

# Set timezone. (repeat safe)
echo "Setting timezone information."
dpkg-reconfigure tzdata || exit 6


#-------------------------------------------------------------------------------
# Update server software

# Update the stuff that exists. (repeat safe)
echo "Updating server packages."
aptitude update || exit 7
aptitude safe-upgrade || exit 8
aptitude full-upgrade || exit 9

# Add some core packages. (repeat safe)
echo "Installing core packages."
aptitude install build-essential bash-completion dnsutils || exit 10


#-------------------------------------------------------------------------------
# Setup bash configuration files for root

# Copy root shell environment. (repeat safe)
echo "Copying default root shell environment."
cp -f "$INIT_DIR/root.bashrc" ~/.bashrc || exit 11
cp -f "$INIT_DIR/user.bash_aliases" ~/.bash_aliases || exit 12

# Copy default user environment. (repeat safe)
echo "Copying default user shell environment."
cp -f "$INIT_DIR/user.bashrc" /etc/skel/.bashrc || exit 13
cp -f "$INIT_DIR/user.bash_aliases" /etc/skel/.bash_aliases || exit 14


#-------------------------------------------------------------------------------
# Setup basic IP tables

# (repeat safe)
echo "Setting up ip tables firewall."
cp "$INIT_DIR/iptables.test.rules" /etc/iptables.test.rules || exit 15

echo "Validating iptables rules."
iptables-restore < /etc/iptables.test.rules || exit 16

echo "Saving ip tables configuration."
iptables-save > /etc/iptables.up.rules || exit 17

# Setup network adaptors to automatically restore the up rules (NOT repeat safe)
echo "Saving startup command to network interface configuration."
echo -e "\npre-up iptables-restore < /etc/iptables.up.rules" >> /etc/network/interfaces || exit 18


#-------------------------------------------------------------------------------
# Grant administrative user group sudo privileges

echo "Creating sudoers lock file."
if [ -f "/etc/sudoers.tmp" ]
then
  exit 19
fi

touch /etc/sudoers.tmp || exit 20

echo "Validating sudoers configurations."
visudo -c -f "$INIT_DIR/sudoers" || exit 21

echo "Copying sudoers configurations."
cp "$INIT_DIR/sudoers" /etc/sudoers || exit 22

echo "Removing sudoers lock file."
rm /etc/sudoers.tmp || exit 23


#-------------------------------------------------------------------------------
# Edit the Secure Shell configuration directives.

echo "Copying SSH configurations."
cp -f "$INIT_DIR/sshd_config" /etc/ssh/sshd_config || exit 24

echo "Validating SSH configurations."
/etc/init.d/ssh reload || exit 25


#-------------------------------------------------------------------------------
# Add administrative user

echo "Adding administrative user."
adduser admin || exit 26


#-------------------------------------------------------------------------------
# Restart server

reboot


 