#!/bin/bash
#-------------------------------------------------------------------------------
#
# upgrade_server
#
#-------------------------------------------------------------------------------
# Start

echo "Updating server packages."

aptitude update || exit 1
aptitude safe-upgrade || exit 2
aptitude full-upgrade || exit 3


echo "Make sure some core packages are installed."

aptitude install build-essential \
                 bash-completion \
                 dnsutils \
|| exit 4